//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockParadise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cart
    {
        public int id { get; set; }
        [Display(Name = "ID User")]
        public Nullable<int> id_user { get; set; }
        [Display(Name = "ID Product")]
        public Nullable<int> id_product { get; set; }
        [Display(Name = "Quantity")]
        public Nullable<int> number_of { get; set; }
        [Display(Name = "Creat at")]

        public Nullable<System.DateTime> created_at { get; set; }

        [Display(Name = "Username")]


        public virtual account account { get; set; }
        [Display(Name = "Name product")]

        public virtual product product { get; set; }
    }
}
