//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockParadise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user_order
    {
        [Display(Name = "ID")]
        public int id { get; set; }
        [Display(Name = "ID User")]
        public int id_user { get; set; }
        [Display(Name = "Odert time")]
        public Nullable<System.DateTime> order_time { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
        [Display(Name = "Info Order")]
        public string OrderItemsJSON { get; set; }

        [Display(Name = "Total Pridce $")]
        public Nullable<double> total_price { get; set; }

        public virtual account account { get; set; }
    }
}
